<a href="https://colab.research.google.com/github/Shahzodbey/real_projects/blob/main/absenteeism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
raw_csv_data = pd.read_csv('/content/drive/MyDrive/data science/notebooks/Absenteeism_data.csv')

In [ ]:
raw_csv_data

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,3,23,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,10,22,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,20,23,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,14,19,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,1,22,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,20,1,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,20,1,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,20,11,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,3,11,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,24,14,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,3,23,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,3,21,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,6,11,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,33,23,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,18,10,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,3,11,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,10,13,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,20,28,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,11,18,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,10,25,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,11,23,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,30,28,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,11,18,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,3,23,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,3,18,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,2,18,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,1,23,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,2,18,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,3,23,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,10,23,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,11,24,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,19,11,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,2,28,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,20,23,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,27,23,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,34,23,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,3,23,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,5,19,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,14,23,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,34,23,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,3,23,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,15,23,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,20,22,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,15,14,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,20,0,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,29,0,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,28,23,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,34,23,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,11,0,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,36,0,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,28,18,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,3,23,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,13,0,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,33,23,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,3,23,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,20,23,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,3,23,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,34,23,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,36,0,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,22,23,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,3,23,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,28,23,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,34,23,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,28,23,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,33,23,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,15,23,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,3,23,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,28,23,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,20,19,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,15,14,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,28,28,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,11,26,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,10,23,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,20,28,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,3,23,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,28,23,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,3,13,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,17,21,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,15,23,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,14,10,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,6,22,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,15,14,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,14,6,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,17,21,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,28,13,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,20,28,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,33,28,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,28,28,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,11,7,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,15,23,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,33,23,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,34,19,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,36,23,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,1,26,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,28,23,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,20,26,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,34,19,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,10,22,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,28,28,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,20,28,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,28,23,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,10,22,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,34,27,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,24,19,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,28,23,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,28,23,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,34,19,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,34,27,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,14,18,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,28,27,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,27,23,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,28,28,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,28,27,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,28,27,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,34,27,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,34,27,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,22,18,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,11,18,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,27,23,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,34,27,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,34,27,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,28,23,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,11,22,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,27,23,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,24,1,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,3,11,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,14,28,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,6,23,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,20,28,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,11,22,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,31,11,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,31,1,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,28,28,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,28,23,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,22,23,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,27,23,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,28,25,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,18,18,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,18,23,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,28,23,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,6,19,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,19,28,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,20,19,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,30,19,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,17,17,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,15,22,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,20,13,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,22,13,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,33,14,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,20,13,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,17,11,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,14,1,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,20,26,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,14,13,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,11,6,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,17,8,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,20,28,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,28,23,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,7,14,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,3,13,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,28,23,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,28,11,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,22,13,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,28,11,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,28,11,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,3,13,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,7,14,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,28,28,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,33,14,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,28,28,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,15,28,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,28,23,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,14,28,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,24,13,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,14,23,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,28,28,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,20,28,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,3,13,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,36,23,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,15,23,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,24,14,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,15,28,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,33,28,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,20,19,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,11,19,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,14,12,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,23,19,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,11,13,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,1,7,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,2,0,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,14,28,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,14,28,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,3,18,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,28,19,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,27,7,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,14,28,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,3,12,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,7,0,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,18,0,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,23,0,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,31,0,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,3,11,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,36,13,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,10,22,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,24,19,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,10,22,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,24,10,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,15,23,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,24,10,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,3,11,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,14,23,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,24,10,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,36,13,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,1,13,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,36,23,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,36,13,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,23,22,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,3,11,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,32,28,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,28,28,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,14,19,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,36,1,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,34,5,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,34,26,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,18,26,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,22,18,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,14,25,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,18,1,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,18,1,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,30,25,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,10,22,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,11,26,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,3,26,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,11,19,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,11,19,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,20,0,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,11,19,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,30,19,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,11,23,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,9,18,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,26,13,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,26,14,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,20,28,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,11,23,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,33,23,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,21,11,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,22,23,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,36,13,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,33,25,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,1,23,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,36,23,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,1,19,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,10,8,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,27,6,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,3,11,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,3,23,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,11,19,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,5,0,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,24,9,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,15,28,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,8,0,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,19,0,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,3,13,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,24,9,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,3,23,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,20,28,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,5,26,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,36,28,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,5,0,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,15,7,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,3,13,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,11,24,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,1,26,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,11,26,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,11,22,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,36,0,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,33,0,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,22,1,12/10/2016,179,26,30,265.017,19,3,0,0,8
296,34,7,12/10/2016,118,10,37,265.017,28,1,0,0,3
297,13,22,12/10/2016,369,17,31,265.017,25,1,3,0,8
298,3,28,14/10/2016,179,51,38,265.017,31,1,0,0,1
299,22,1,14/10/2016,179,26,30,265.017,19,3,0,0,64
300,5,0,14/10/2016,235,20,43,265.017,38,1,1,0,0
301,11,19,15/10/2016,289,36,33,265.017,30,1,2,1,16
302,20,28,16/10/2016,260,50,36,265.017,23,1,4,0,3
303,5,0,16/10/2016,235,20,43,265.017,38,1,1,0,0
304,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
305,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
306,36,28,20/10/2016,118,13,50,265.017,31,1,1,0,1
307,15,28,20/10/2016,291,31,40,265.017,25,1,1,1,4
308,22,23,22/10/2016,179,26,30,265.017,19,3,0,0,16
309,36,28,22/10/2016,118,13,50,265.017,31,1,1,0,1
310,10,10,26/10/2016,361,52,28,265.017,27,1,1,4,8
311,20,0,27/10/2016,260,50,36,265.017,23,1,4,0,0
312,15,0,27/10/2016,291,31,40,265.017,25,1,1,1,0
313,30,0,27/10/2016,157,27,29,265.017,22,1,0,0,0
314,22,1,28/10/2016,179,26,30,265.017,19,3,0,0,5
315,22,7,28/10/2016,179,26,30,265.017,19,3,0,0,5
316,36,23,29/10/2016,118,13,50,265.017,31,1,1,0,1
317,34,11,07/11/2016,118,10,37,284.031,28,1,0,0,8
318,33,23,07/11/2016,248,25,47,284.031,32,1,2,1,2
319,3,6,08/11/2016,179,51,38,284.031,31,1,0,0,8
320,20,28,11/11/2016,260,50,36,284.031,23,1,4,0,3
321,15,23,14/11/2016,291,31,40,284.031,25,1,1,1,1
322,23,1,14/11/2016,378,49,36,284.031,21,1,2,4,8
323,14,11,14/11/2016,155,12,34,284.031,25,1,2,0,120
324,5,26,14/11/2016,235,20,43,284.031,38,1,1,0,8
325,18,0,15/11/2016,330,16,28,284.031,25,2,0,0,0
326,1,18,16/11/2016,235,11,37,284.031,29,3,1,1,1
327,34,11,16/11/2016,118,10,37,284.031,28,1,0,0,3
328,1,25,17/11/2016,235,11,37,284.031,29,3,1,1,2
329,3,28,17/11/2016,179,51,38,284.031,31,1,0,0,3
330,24,13,18/11/2016,246,25,41,284.031,23,1,0,0,8
331,15,12,18/11/2016,291,31,40,284.031,25,1,1,1,4
332,24,13,21/11/2016,246,25,41,284.031,23,1,0,0,8
333,3,28,22/11/2016,179,51,38,284.031,31,1,0,0,1
334,20,10,23/11/2016,260,50,36,284.031,23,1,4,0,8
335,20,15,25/11/2016,260,50,36,284.031,23,1,4,0,8
336,23,0,25/11/2016,378,49,36,284.031,21,1,2,4,0
337,7,0,29/11/2016,279,5,39,284.031,24,1,2,0,0
338,3,23,24/11/2016,179,51,38,284.031,31,1,0,0,1
339,28,12,05/12/2016,225,26,28,236.629,24,1,1,2,3
340,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,2
341,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,1
342,1,23,05/12/2016,235,11,37,236.629,29,3,1,1,3
343,36,28,06/12/2016,118,13,50,236.629,31,1,1,0,1
344,20,28,09/12/2016,260,50,36,236.629,23,1,4,0,4
345,24,4,15/12/2016,246,25,41,236.629,23,1,0,0,8
346,3,28,15/12/2016,179,51,38,236.629,31,1,0,0,1
347,3,28,16/12/2016,179,51,38,236.629,31,1,0,0,1
348,22,23,20/12/2016,179,26,30,236.629,19,3,0,0,1
349,34,25,20/12/2016,118,10,37,236.629,28,1,0,0,8
350,1,25,22/12/2016,235,11,37,236.629,29,3,1,1,2
351,3,28,23/12/2016,179,51,38,236.629,31,1,0,0,1
352,5,13,20/12/2016,235,20,43,236.629,38,1,1,0,8
353,1,14,20/12/2016,235,11,37,236.629,29,3,1,1,4
354,20,26,21/12/2016,260,50,36,236.629,23,1,4,0,8
355,30,28,19/12/2016,157,27,29,236.629,22,1,0,0,2
356,3,28,19/12/2016,179,51,38,236.629,31,1,0,0,3
357,11,19,19/12/2016,289,36,33,236.629,30,1,2,1,8
358,28,23,04/01/2017,225,26,28,330.061,24,1,1,2,5
359,34,19,09/01/2017,118,10,37,330.061,28,1,0,0,32
360,14,23,09/01/2017,155,12,34,330.061,25,1,2,0,2
361,1,13,03/01/2017,235,11,37,330.061,29,3,1,1,1
362,14,23,03/01/2017,155,12,34,330.061,25,1,2,0,4
363,11,26,09/01/2017,289,36,33,330.061,30,1,2,1,8
364,15,3,11/01/2017,291,31,40,330.061,25,1,1,1,8
365,5,26,16/01/2017,235,20,43,330.061,38,1,1,0,8
366,36,26,16/01/2017,118,13,50,330.061,31,1,1,0,4
367,3,28,25/01/2017,179,51,38,330.061,31,1,0,0,1
368,3,28,27/01/2017,179,51,38,330.061,31,1,0,0,1
369,34,28,07/02/2017,118,10,37,251.818,28,1,0,0,2
370,3,27,01/02/2017,179,51,38,251.818,31,1,0,0,3
371,28,7,01/02/2017,225,26,28,251.818,24,1,1,2,1
372,11,22,03/02/2017,289,36,33,251.818,30,1,2,1,3
373,20,28,10/02/2017,260,50,36,251.818,23,1,4,0,3
374,3,23,17/02/2017,179,51,38,251.818,31,1,0,0,3
375,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,2
376,3,27,15/02/2017,179,51,38,251.818,31,1,0,0,3
377,3,10,16/02/2017,179,51,38,251.818,31,1,0,0,8
378,24,26,16/02/2017,246,25,41,251.818,23,1,0,0,8
379,3,27,17/02/2017,179,51,38,251.818,31,1,0,0,3
380,6,22,13/02/2017,189,29,33,251.818,25,1,2,2,8
381,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,3
382,24,23,21/02/2017,246,25,41,251.818,23,1,0,0,2
383,15,23,21/02/2017,291,31,40,251.818,25,1,1,1,2
384,30,11,22/02/2017,157,27,29,251.818,22,1,0,0,16
385,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
386,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
387,24,10,24/02/2017,246,25,41,251.818,23,1,0,0,24
388,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
389,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
390,34,18,07/03/2017,118,10,37,244.387,28,1,0,0,8
391,24,19,08/03/2017,246,25,41,244.387,23,1,0,0,16
392,24,28,10/03/2017,246,25,41,244.387,23,1,0,0,2
393,20,28,10/03/2017,260,50,36,244.387,23,1,4,0,4
394,3,28,13/03/2017,179,51,38,244.387,31,1,0,0,2
395,1,22,13/03/2017,235,11,37,244.387,29,3,1,1,8
396,17,22,14/03/2017,179,22,40,244.387,22,2,2,0,8
397,23,22,14/03/2017,378,49,36,244.387,21,1,2,4,8
398,3,28,20/03/2017,179,51,38,244.387,31,1,0,0,16
399,10,22,22/03/2017,361,52,28,244.387,27,1,1,4,8
400,13,0,22/03/2017,369,17,31,244.387,25,1,3,0,0

## First checkpoint

In [ ]:
df = raw_csv_data.copy()

In [ ]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [ ]:
display(df)

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,3,23,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,10,22,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,20,23,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,14,19,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,1,22,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,20,1,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,20,1,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,20,11,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,3,11,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,24,14,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,3,23,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,3,21,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,6,11,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,33,23,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,18,10,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,3,11,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,10,13,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,20,28,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,11,18,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,10,25,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,11,23,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,30,28,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,11,18,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,3,23,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,3,18,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,2,18,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,1,23,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,2,18,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,3,23,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,10,23,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,11,24,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,19,11,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,2,28,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,20,23,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,27,23,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,34,23,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,3,23,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,5,19,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,14,23,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,34,23,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,3,23,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,15,23,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,20,22,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,15,14,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,20,0,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,29,0,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,28,23,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,34,23,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,11,0,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,36,0,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,28,18,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,3,23,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,13,0,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,33,23,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,3,23,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,20,23,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,3,23,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,34,23,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,36,0,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,22,23,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,3,23,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,28,23,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,34,23,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,28,23,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,33,23,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,15,23,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,3,23,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,28,23,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,20,19,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,15,14,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,28,28,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,11,26,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,10,23,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,20,28,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,3,23,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,28,23,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,3,13,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,17,21,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,15,23,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,14,10,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,6,22,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,15,14,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,14,6,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,17,21,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,28,13,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,20,28,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,33,28,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,28,28,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,11,7,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,15,23,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,33,23,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,34,19,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,36,23,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,1,26,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,28,23,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,20,26,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,34,19,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,10,22,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,28,28,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,20,28,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,28,23,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,10,22,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,34,27,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,24,19,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,28,23,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,28,23,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,34,19,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,34,27,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,14,18,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,28,27,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,27,23,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,28,28,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,28,27,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,28,27,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,34,27,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,34,27,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,22,18,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,11,18,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,27,23,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,34,27,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,34,27,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,28,23,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,11,22,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,27,23,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,24,1,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,3,11,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,14,28,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,6,23,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,20,28,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,11,22,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,31,11,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,31,1,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,28,28,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,28,23,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,22,23,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,27,23,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,28,25,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,18,18,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,18,23,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,28,23,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,6,19,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,19,28,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,20,19,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,30,19,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,17,17,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,15,22,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,20,13,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,22,13,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,33,14,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,20,13,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,17,11,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,14,1,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,20,26,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,14,13,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,11,6,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,17,8,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,20,28,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,28,23,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,7,14,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,3,13,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,28,23,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,28,11,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,22,13,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,28,11,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,28,11,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,3,13,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,7,14,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,28,28,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,33,14,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,28,28,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,15,28,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,28,23,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,14,28,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,24,13,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,14,23,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,28,28,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,20,28,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,3,13,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,36,23,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,15,23,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,24,14,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,15,28,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,33,28,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,20,19,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,11,19,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,14,12,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,23,19,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,11,13,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,1,7,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,2,0,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,14,28,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,14,28,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,3,18,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,28,19,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,27,7,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,14,28,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,3,12,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,7,0,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,18,0,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,23,0,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,31,0,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,3,11,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,36,13,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,10,22,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,24,19,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,10,22,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,24,10,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,15,23,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,24,10,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,3,11,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,14,23,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,24,10,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,36,13,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,1,13,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,36,23,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,36,13,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,23,22,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,3,11,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,32,28,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,28,28,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,14,19,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,36,1,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,34,5,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,34,26,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,18,26,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,22,18,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,14,25,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,18,1,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,18,1,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,30,25,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,10,22,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,11,26,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,3,26,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,11,19,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,11,19,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,20,0,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,11,19,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,30,19,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,11,23,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,9,18,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,26,13,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,26,14,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,20,28,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,11,23,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,33,23,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,21,11,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,22,23,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,36,13,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,33,25,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,1,23,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,36,23,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,1,19,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,10,8,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,27,6,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,3,11,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,3,23,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,11,19,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,5,0,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,24,9,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,15,28,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,8,0,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,19,0,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,3,13,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,24,9,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,3,23,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,20,28,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,5,26,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,36,28,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,5,0,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,15,7,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,3,13,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,11,24,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,1,26,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,11,26,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,11,22,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,36,0,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,33,0,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,22,1,12/10/2016,179,26,30,265.017,19,3,0,0,8
296,34,7,12/10/2016,118,10,37,265.017,28,1,0,0,3
297,13,22,12/10/2016,369,17,31,265.017,25,1,3,0,8
298,3,28,14/10/2016,179,51,38,265.017,31,1,0,0,1
299,22,1,14/10/2016,179,26,30,265.017,19,3,0,0,64
300,5,0,14/10/2016,235,20,43,265.017,38,1,1,0,0
301,11,19,15/10/2016,289,36,33,265.017,30,1,2,1,16
302,20,28,16/10/2016,260,50,36,265.017,23,1,4,0,3
303,5,0,16/10/2016,235,20,43,265.017,38,1,1,0,0
304,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
305,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
306,36,28,20/10/2016,118,13,50,265.017,31,1,1,0,1
307,15,28,20/10/2016,291,31,40,265.017,25,1,1,1,4
308,22,23,22/10/2016,179,26,30,265.017,19,3,0,0,16
309,36,28,22/10/2016,118,13,50,265.017,31,1,1,0,1
310,10,10,26/10/2016,361,52,28,265.017,27,1,1,4,8
311,20,0,27/10/2016,260,50,36,265.017,23,1,4,0,0
312,15,0,27/10/2016,291,31,40,265.017,25,1,1,1,0
313,30,0,27/10/2016,157,27,29,265.017,22,1,0,0,0
314,22,1,28/10/2016,179,26,30,265.017,19,3,0,0,5
315,22,7,28/10/2016,179,26,30,265.017,19,3,0,0,5
316,36,23,29/10/2016,118,13,50,265.017,31,1,1,0,1
317,34,11,07/11/2016,118,10,37,284.031,28,1,0,0,8
318,33,23,07/11/2016,248,25,47,284.031,32,1,2,1,2
319,3,6,08/11/2016,179,51,38,284.031,31,1,0,0,8
320,20,28,11/11/2016,260,50,36,284.031,23,1,4,0,3
321,15,23,14/11/2016,291,31,40,284.031,25,1,1,1,1
322,23,1,14/11/2016,378,49,36,284.031,21,1,2,4,8
323,14,11,14/11/2016,155,12,34,284.031,25,1,2,0,120
324,5,26,14/11/2016,235,20,43,284.031,38,1,1,0,8
325,18,0,15/11/2016,330,16,28,284.031,25,2,0,0,0
326,1,18,16/11/2016,235,11,37,284.031,29,3,1,1,1
327,34,11,16/11/2016,118,10,37,284.031,28,1,0,0,3
328,1,25,17/11/2016,235,11,37,284.031,29,3,1,1,2
329,3,28,17/11/2016,179,51,38,284.031,31,1,0,0,3
330,24,13,18/11/2016,246,25,41,284.031,23,1,0,0,8
331,15,12,18/11/2016,291,31,40,284.031,25,1,1,1,4
332,24,13,21/11/2016,246,25,41,284.031,23,1,0,0,8
333,3,28,22/11/2016,179,51,38,284.031,31,1,0,0,1
334,20,10,23/11/2016,260,50,36,284.031,23,1,4,0,8
335,20,15,25/11/2016,260,50,36,284.031,23,1,4,0,8
336,23,0,25/11/2016,378,49,36,284.031,21,1,2,4,0
337,7,0,29/11/2016,279,5,39,284.031,24,1,2,0,0
338,3,23,24/11/2016,179,51,38,284.031,31,1,0,0,1
339,28,12,05/12/2016,225,26,28,236.629,24,1,1,2,3
340,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,2
341,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,1
342,1,23,05/12/2016,235,11,37,236.629,29,3,1,1,3
343,36,28,06/12/2016,118,13,50,236.629,31,1,1,0,1
344,20,28,09/12/2016,260,50,36,236.629,23,1,4,0,4
345,24,4,15/12/2016,246,25,41,236.629,23,1,0,0,8
346,3,28,15/12/2016,179,51,38,236.629,31,1,0,0,1
347,3,28,16/12/2016,179,51,38,236.629,31,1,0,0,1
348,22,23,20/12/2016,179,26,30,236.629,19,3,0,0,1
349,34,25,20/12/2016,118,10,37,236.629,28,1,0,0,8
350,1,25,22/12/2016,235,11,37,236.629,29,3,1,1,2
351,3,28,23/12/2016,179,51,38,236.629,31,1,0,0,1
352,5,13,20/12/2016,235,20,43,236.629,38,1,1,0,8
353,1,14,20/12/2016,235,11,37,236.629,29,3,1,1,4
354,20,26,21/12/2016,260,50,36,236.629,23,1,4,0,8
355,30,28,19/12/2016,157,27,29,236.629,22,1,0,0,2
356,3,28,19/12/2016,179,51,38,236.629,31,1,0,0,3
357,11,19,19/12/2016,289,36,33,236.629,30,1,2,1,8
358,28,23,04/01/2017,225,26,28,330.061,24,1,1,2,5
359,34,19,09/01/2017,118,10,37,330.061,28,1,0,0,32
360,14,23,09/01/2017,155,12,34,330.061,25,1,2,0,2
361,1,13,03/01/2017,235,11,37,330.061,29,3,1,1,1
362,14,23,03/01/2017,155,12,34,330.061,25,1,2,0,4
363,11,26,09/01/2017,289,36,33,330.061,30,1,2,1,8
364,15,3,11/01/2017,291,31,40,330.061,25,1,1,1,8
365,5,26,16/01/2017,235,20,43,330.061,38,1,1,0,8
366,36,26,16/01/2017,118,13,50,330.061,31,1,1,0,4
367,3,28,25/01/2017,179,51,38,330.061,31,1,0,0,1
368,3,28,27/01/2017,179,51,38,330.061,31,1,0,0,1
369,34,28,07/02/2017,118,10,37,251.818,28,1,0,0,2
370,3,27,01/02/2017,179,51,38,251.818,31,1,0,0,3
371,28,7,01/02/2017,225,26,28,251.818,24,1,1,2,1
372,11,22,03/02/2017,289,36,33,251.818,30,1,2,1,3
373,20,28,10/02/2017,260,50,36,251.818,23,1,4,0,3
374,3,23,17/02/2017,179,51,38,251.818,31,1,0,0,3
375,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,2
376,3,27,15/02/2017,179,51,38,251.818,31,1,0,0,3
377,3,10,16/02/2017,179,51,38,251.818,31,1,0,0,8
378,24,26,16/02/2017,246,25,41,251.818,23,1,0,0,8
379,3,27,17/02/2017,179,51,38,251.818,31,1,0,0,3
380,6,22,13/02/2017,189,29,33,251.818,25,1,2,2,8
381,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,3
382,24,23,21/02/2017,246,25,41,251.818,23,1,0,0,2
383,15,23,21/02/2017,291,31,40,251.818,25,1,1,1,2
384,30,11,22/02/2017,157,27,29,251.818,22,1,0,0,16
385,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
386,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
387,24,10,24/02/2017,246,25,41,251.818,23,1,0,0,24
388,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
389,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
390,34,18,07/03/2017,118,10,37,244.387,28,1,0,0,8
391,24,19,08/03/2017,246,25,41,244.387,23,1,0,0,16
392,24,28,10/03/2017,246,25,41,244.387,23,1,0,0,2
393,20,28,10/03/2017,260,50,36,244.387,23,1,4,0,4
394,3,28,13/03/2017,179,51,38,244.387,31,1,0,0,2
395,1,22,13/03/2017,235,11,37,244.387,29,3,1,1,8
396,17,22,14/03/2017,179,22,40,244.387,22,2,2,0,8
397,23,22,14/03/2017,378,49,36,244.387,21,1,2,4,8
398,3,28,20/03/2017,179,51,38,244.387,31,1,0,0,16
399,10,22,22/03/2017,361,52,28,244.387,27,1,1,4,8
400,13,0,22/03/2017,369,17,31,244.387,25,1,3,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    object
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB

## Drop ID

In [ ]:
df = df.drop(['ID'], axis=1)

In [ ]:
df.head()

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [ ]:
df['Reason for Absence']

0      26
1       0
2      23
3       7
4      23
5      23
6      22
7      23
8      19
9      22
10      1
11      1
12     11
13     11
14     23
15     14
16     23
17     21
18     11
19     23
20     10
21     11
22     13
23     28
24     18
25     25
26     23
27     28
28     18
29     23
30     18
31     18
32     23
33     18
34     23
35     23
36     24
37     11
38     28
39     23
40     23
41     23
42     23
43     19
44     23
45     23
46     23
47     23
48     22
49     14
50      0
51      0
52     23
53     23
54      0
55      0
56     18
57     23
58      0
59     23
60     23
61     23
62     23
63     23
64      0
65     23
66     23
67     23
68     23
69     23
70     23
71     23
72     23
73     23
74     19
75     14
76     28
77     26
78     23
79     28
80     23
81     23
82     13
83     21
84     23
85     10
86     22
87     14
88     23
89      6
90     23
91     21
92     13
93     28
94     28
95     28
96      7
97     23
98     23
99     19
100    23
101    26
102    23
103    26
104    19
105    22
106    28
107    28
108    23
109    22
110    27
111    19
112    23
113    23
114    19
115    27
116    18
117    27
118    23
119    28
120    27
121    27
122    27
123    27
124    27
125    27
126    27
127    27
128    27
129    18
130    18
131    27
132    23
133    27
134    27
135    23
136    22
137    23
138     1
139    11
140    28
141    23
142    28
143    22
144    11
145     1
146    28
147    23
148    23
149    23
150    25
151    18
152    23
153    23
154    19
155    28
156    19
157    19
158    17
159    22
160    13
161    13
162    14
163    13
164    11
165     1
166    26
167    13
168     6
169     8
170    28
171    23
172    14
173    13
174    23
175    11
176    13
177    11
178    11
179    13
180    14
181    28
182    14
183    28
184    28
185    23
186    28
187    13
188    23
189    28
190    28
191    13
192    23
193    23
194    14
195    28
196    28
197    19
198    19
199    12
200    19
201    13
202     7
203     0
204    13
205    28
206    28
207    18
208    19
209     7
210    28
211    12
212    13
213     0
214     0
215     0
216     0
217    11
218    13
219    22
220    19
221    22
222    10
223    23
224    10
225    11
226    23
227    10
228    13
229    13
230    23
231    13
232    22
233    11
234    28
235    28
236    19
237     1
238     5
239    26
240    26
241    18
242    25
243     1
244     1
245    25
246    22
247    26
248    26
249    19
250    19
251     0
252    19
253    19
254    23
255    18
256    13
257    14
258    28
259    23
260    23
261    11
262    23
263    13
264    25
265    23
266    23
267    19
268     8
269     6
270    11
271    23
272    19
273     0
274     9
275    28
276     0
277     0
278    13
279     9
280    23
281    28
282    28
283    26
284    28
285     0
286    28
287     7
288    13
289    24
290    26
291    26
292    22
293     0
294     0
295     1
296     7
297    22
298    28
299     1
300     0
301    19
302    28
303     0
304    23
305    23
306    28
307    28
308    23
309    28
310    10
311     0
312     0
313     0
314     1
315     7
316    23
317    11
318    23
319     6
320    28
321    23
322     1
323    11
324    26
325     0
326    18
327    11
328    25
329    28
330    13
331    12
332    13
333    28
334    10
335    15
336     0
337     0
338    23
339    12
340    28
341    28
342    23
343    28
344    28
345     4
346    28
347    28
348    23
349    25
350    25
351    28
352    13
353    14
354    26
355    28
356    28
357    19
358    23
359    19
360    23
361    13
362    23
363    26
364     3
365    26
366    26
367    28
368    28
369    28
370    27
371     7
372    22
373    28
374    23
375    27
376    27
377    10
378    26
379    27
380    22
381    27
382    23
383    23
384    11
385    27
386    27
387    10
388    27
389    27
390    18
391    19
392    28
393    28
394    28
395    22
396    22
397    22
398    28
399    22
400     0
401    21
402    23
403    14
404    13
405     0
406     0
407     0
408    28
409    22
410    19
411    28
412    28
413    28
414    26
415    22
416    26
417    23
418    28
419    23
420    13
421    28
422    28
423    28
424    11
425    13
426    23
427    10
428    23
429    28
430    23
431    28
432    11
433     8
434    18
435    25
436    13
437    25
438    28
439     1
440    23
441    23
442    28
443    28
444    23
445    28
446     0
447    13
448    28
449    28
450    28
451    26
452    28
453    23
454    23
455     5
456    21
457    28
458    11
459    13
460    23
461    25
462    13
463     7
464    25
465    26
466    26
467    28
468    15
469    23
470    28
471     9
472    28
473    23
474    22
475    22
476    26
477    28
478    28
479    23
480    25
481    25
482    28
483    28
484    26
485    26
486    28
487    25
488    25
489    23
490    23
491    28
492    28
493    28
494    28
495    28
496    28
497    28
498    23
499    28
500    23
501    23
502    23
503    23
504    23
505    23
506    22
507     4
508    11
509    26
510    14
511    28
512    23
513    23
514    23
515    23
516    23
517    23
518    23
519    26
520    28
521     1
522    23
523    10
524    13
525    10
526    10
527    23
528     6
529    10
530     0
531    13
532    21
533    28
534     2
535    28
536     9
537    24
538     1
539    23
540    22
541    28
542    13
543    14
544    28
545    23
546     8
547    23
548     0
549     0
550    14
551     0
552    23
553    26
554    28
555    13
556    28
557    23
558    13
559    23
560    23
561    14
562    18
563    26
564    18
565    13
566    23
567    23
568    23
569    18
570    12
571    12
572    25
573    25
574    13
575    25
576    10
577    18
578    27
579    18
580    27
581    27
582    13
583    27
584    27
585    13
586    23
587     1
588    27
589    28
590    27
591    27
592    28
593    27
594    19
595    27
596     7
597    27
598    27
599    25
600    13
601    23
602    27
603    12
604    27
605    27
606    13
607    27
608    25
609    25
610    27
611     7
612    27
613    23
614    25
615    27
616    27
617    25
618    27
619    23
620    25
621    25
622    12
623    27
624    27
625    27
626    25
627    27
628    25
629    19
630    13
631    27
632    27
633    27
634    10
635    13
636    27
637     7
638    27
639    23
640    25
641    27
642    23
643    27
644    23
645    27
646    27
647    23
648    13
649    27
650    27
651    13
652    19
653    22
654    13
655    10
656    19
657    19
658    13
659    27
660     7
661    16
662    23
663    23
664    10
665    22
666    27
667    19
668    16
669    27
670    28
671    19
672    14
673    27
674    22
675    19
676    28
677     8
678    26
679    13
680    28
681    14
682    19
683    22
684    27
685    23
686     5
687    28
688     0
689    27
690     0
691    16
692    10
693    10
694    22
695    10
696     6
697    10
698    23
699    28
Name: Reason for Absence, dtype: int64

In [ ]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [ ]:
len(df['Reason for Absence'].unique())

28

In [ ]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [ ]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

## New categorical columns

In [ ]:
reasons_column = pd.get_dummies(df['Reason for Absence'])

In [ ]:
reasons_column

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
10,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
50,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
51,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
53,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
54,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
55,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
56,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
58,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
62,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
64,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
67,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
68,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
69,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
72,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
74,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
76,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
77,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
78,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
82,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
84,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
85,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
87,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
89,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
91,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
92,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
93,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
95,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
96,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
106,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
107,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
109,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
111,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
112,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
113,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
114,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
115,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
117,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
118,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
119,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
120,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
121,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
122,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
124,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
126,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
127,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
129,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
130,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
132,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
133,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
134,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
135,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
138,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
140,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
141,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
142,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
143,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
144,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
145,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
147,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
148,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
149,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
152,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
153,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
154,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
155,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
156,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
157,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
158,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
159,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
160,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
161,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
162,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
163,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
164,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
165,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
166,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
167,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
168,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
169,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
170,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
172,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
173,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
174,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
175,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
176,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
177,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
178,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
179,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
181,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
182,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
183,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
184,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
185,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
186,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
187,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
188,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
189,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
190,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
191,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
192,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
193,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
194,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
196,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
197,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
198,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
199,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
201,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
202,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
203,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
204,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
205,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
206,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
207,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
208,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
209,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
210,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
211,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
212,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
213,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
214,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
215,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
216,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
217,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
218,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
219,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
220,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
221,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
222,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
223,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
224,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
225,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
226,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
227,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
228,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
229,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
230,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
231,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
232,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
233,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
234,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
235,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
236,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
237,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
238,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
239,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
240,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
241,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
242,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
243,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
244,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
245,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
246,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
247,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
248,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
249,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
250,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
251,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
252,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
253,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
254,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
256,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
257,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
258,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
259,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
260,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
261,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
262,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
263,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
265,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
266,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
267,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
268,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
269,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
270,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
271,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
272,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
273,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
274,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
275,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
276,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
277,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
278,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
279,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
280,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
281,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
282,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
283,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
284,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
285,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
286,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
287,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
288,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
289,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
290,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
291,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
292,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
293,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
294,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
295,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
296,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
297,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
298,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
299,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
300,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
301,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
302,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
303,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
304,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
305,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
306,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
307,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
308,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
309,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
310,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
311,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
312,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
313,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
314,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
315,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
316,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
317,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
318,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
319,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
320,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
321,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
322,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
323,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
324,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
325,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
326,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
327,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
328,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
329,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
330,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
331,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
332,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
reasons_column['check'] = reasons_column.sum(axis=1)
reasons_column.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,check
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1

In [ ]:
reasons_column['check'].unique()

array([1])

In [ ]:
reasons_column = reasons_column.drop(['check'], axis=1)
reasons_column.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [ ]:
reasons_column = pd.get_dummies(df['Reason for Absence'], drop_first=True)

In [ ]:
reasons_column.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

## Drop Reason for Absence

In [ ]:
df = df.drop(['Reason for Absence'], axis=1)

In [ ]:
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [ ]:
reasons_column.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [ ]:
reasons_column.loc[:, 1:14].max(axis=1)

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    1
140    0
141    0
142    0
143    0
144    1
145    1
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    1
161    1
162    1
163    1
164    1
165    1
166    0
167    1
168    1
169    1
170    0
171    0
172    1
173    1
174    0
175    1
176    1
177    1
178    1
179    1
180    1
181    0
182    1
183    0
184    0
185    0
186    0
187    1
188    0
189    0
190    0
191    1
192    0
193    0
194    1
195    0
196    0
197    0
198    0
199    1
200    0
201    1
202    1
203    0
204    1
205    0
206    0
207    0
208    0
209    1
210    0
211    1
212    1
213    0
214    0
215    0
216    0
217    1
218    1
219    0
220    0
221    0
222    1
223    0
224    1
225    1
226    0
227    1
228    1
229    1
230    0
231    1
232    0
233    1
234    0
235    0
236    0
237    1
238    1
239    0
240    0
241    0
242    0
243    1
244    1
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    0
255    0
256    1
257    1
258    0
259    0
260    0
261    1
262    0
263    1
264    0
265    0
266    0
267    0
268    1
269    1
270    1
271    0
272    0
273    0
274    1
275    0
276    0
277    0
278    1
279    1
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    1
288    1
289    0
290    0
291    0
292    0
293    0
294    0
295    1
296    1
297    0
298    0
299    1
300    0
301    0
302    0
303    0
304    0
305    0
306    0
307    0
308    0
309    0
310    1
311    0
312    0
313    0
314    1
315    1
316    0
317    1
318    0
319    1
320    0
321    0
322    1
323    1
324    0
325    0
326    0
327    1
328    0
329    0
330    1
331    1
332    1
333    0
334    1
335    0
336    0
337    0
338    0
339    1
340    0
341    0
342    0
343    0
344    0
345    1
346    0
347    0
348    0
349    0
350    0
351    0
352    1
353    1
354    0
355    0
356    0
357    0
358    0
359    0
360    0
361    1
362    0
363    0
364    1
365    0
366    0
367    0
368    0
369    0
370    0
371    1
372    0
373    0
374    0
375    0
376    0
377    1
378    0
379    0
380    0
381    0
382    0
383    0
384    1
385    0
386    0
387    1
388    0
389    0
390    0
391    0
392    0
393    0
394    0
395    0
396    0
397    0
398    0
399    0
400    0
401    0
402    0
403    1
404    1
405    0
406    0
407    0
408    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
418    0
419    0
420    1
421    0
422    0
423    0
424    1
425    1
426    0
427    1
428    0
429    0
430    0
431    0
432    1
433    1
434    0
435    0
436    1
437    0
438    0
439    1
440    0
441    0
442    0
443    0
444    0
445    0
446    0
447    1
448    0
449    0
450    0
451    0
452    0
453    0
454    0
455    1
456    0
457    0
458    1
459    1
460    0
461    0
462    1
463    1
464    0
465    0
466    0
467    0
468    0
469    0
470    0
471    1
472    0
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    0
484    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
503    0
504    0
505    0
506    0
507    1
508    1
509    0
510    1
511    0
512    0
513    0
514    0
515    0
516    0
517    0
518    0
519    0
520    0
521    1
522    0
523    1
524    1
525    1
526    1
527    0
528    1
529    1
530    0
531    1
532    0
533    0
534    1
535    0
536    1
537    0
538    1
539    0
540    0
541    0
542    1
543    1
544    0
545    0
546    1
547    0
548    0
549    0
550    1
551    0
552    0
553    0
554    0
555    1
556    0
557    0
558    1
559    0
560    0
561    1
562    0
563    0
564    0
565    1
566    0
567    0
568    0
569    0
570    1
571    1
572    0
573    0
574    1
575    0
576    1
577    0
578    0
579    0
580    0
581    0
582    1
583    0
584    0
585    1
586    0
587    1
588    0
589    0
590    0
591    0
592    0
593    0
594    0
595    0
596    1
597    0
598    0
599    0
600    1
601    0
602    0
603    1
604    0
605    0
606    1
607    0
608    0
609    0
610    0
611    1
612    0
613    0
614    0
615    0
616    0
617    0
618    0
619    0
620    0
621    0
622    1
623    0
624    0
625    0
626    0
627    0
628    0
629    0
630    1
631    0
632    0
633    0
634    1
635    1
636    0
637    1
638    0
639    0
640    0
641    0
642    0
643    0
644    0
645    0
646    0
647    0
648    1
649    0
650    0
651    1
652    0
653    0
654    1
655    1
656    0
657    0
658    1
659    0
660    1
661    0
662    0
663    0
664    1
665    0
666    0
667    0
668    0
669    0
670    0
671    0
672    1
673    0
674    0
675    0
676    0
677    1
678    0
679    1
680    0
681    1
682    0
683    0
684    0
685    0
686    1
687    0
688    0
689    0
690    0
691    0
692    1
693    1
694    0
695    1
696    1
697    1
698    0
699    0
dtype: uint8

## Group common reasons

In [ ]:
reason_type1 = reasons_column.loc[:, 1:14].max(axis=1)
reason_type2 = reasons_column.loc[:, 15:17].max(axis=1)
reason_type3 = reasons_column.loc[:, 18:21].max(axis=1)
reason_type4 = reasons_column.loc[:, 22:].max(axis=1)

In [ ]:
reason_type1

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    1
140    0
141    0
142    0
143    0
144    1
145    1
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    1
161    1
162    1
163    1
164    1
165    1
166    0
167    1
168    1
169    1
170    0
171    0
172    1
173    1
174    0
175    1
176    1
177    1
178    1
179    1
180    1
181    0
182    1
183    0
184    0
185    0
186    0
187    1
188    0
189    0
190    0
191    1
192    0
193    0
194    1
195    0
196    0
197    0
198    0
199    1
200    0
201    1
202    1
203    0
204    1
205    0
206    0
207    0
208    0
209    1
210    0
211    1
212    1
213    0
214    0
215    0
216    0
217    1
218    1
219    0
220    0
221    0
222    1
223    0
224    1
225    1
226    0
227    1
228    1
229    1
230    0
231    1
232    0
233    1
234    0
235    0
236    0
237    1
238    1
239    0
240    0
241    0
242    0
243    1
244    1
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    0
255    0
256    1
257    1
258    0
259    0
260    0
261    1
262    0
263    1
264    0
265    0
266    0
267    0
268    1
269    1
270    1
271    0
272    0
273    0
274    1
275    0
276    0
277    0
278    1
279    1
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    1
288    1
289    0
290    0
291    0
292    0
293    0
294    0
295    1
296    1
297    0
298    0
299    1
300    0
301    0
302    0
303    0
304    0
305    0
306    0
307    0
308    0
309    0
310    1
311    0
312    0
313    0
314    1
315    1
316    0
317    1
318    0
319    1
320    0
321    0
322    1
323    1
324    0
325    0
326    0
327    1
328    0
329    0
330    1
331    1
332    1
333    0
334    1
335    0
336    0
337    0
338    0
339    1
340    0
341    0
342    0
343    0
344    0
345    1
346    0
347    0
348    0
349    0
350    0
351    0
352    1
353    1
354    0
355    0
356    0
357    0
358    0
359    0
360    0
361    1
362    0
363    0
364    1
365    0
366    0
367    0
368    0
369    0
370    0
371    1
372    0
373    0
374    0
375    0
376    0
377    1
378    0
379    0
380    0
381    0
382    0
383    0
384    1
385    0
386    0
387    1
388    0
389    0
390    0
391    0
392    0
393    0
394    0
395    0
396    0
397    0
398    0
399    0
400    0
401    0
402    0
403    1
404    1
405    0
406    0
407    0
408    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
418    0
419    0
420    1
421    0
422    0
423    0
424    1
425    1
426    0
427    1
428    0
429    0
430    0
431    0
432    1
433    1
434    0
435    0
436    1
437    0
438    0
439    1
440    0
441    0
442    0
443    0
444    0
445    0
446    0
447    1
448    0
449    0
450    0
451    0
452    0
453    0
454    0
455    1
456    0
457    0
458    1
459    1
460    0
461    0
462    1
463    1
464    0
465    0
466    0
467    0
468    0
469    0
470    0
471    1
472    0
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    0
484    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
503    0
504    0
505    0
506    0
507    1
508    1
509    0
510    1
511    0
512    0
513    0
514    0
515    0
516    0
517    0
518    0
519    0
520    0
521    1
522    0
523    1
524    1
525    1
526    1
527    0
528    1
529    1
530    0
531    1
532    0
533    0
534    1
535    0
536    1
537    0
538    1
539    0
540    0
541    0
542    1
543    1
544    0
545    0
546    1
547    0
548    0
549    0
550    1
551    0
552    0
553    0
554    0
555    1
556    0
557    0
558    1
559    0
560    0
561    1
562    0
563    0
564    0
565    1
566    0
567    0
568    0
569    0
570    1
571    1
572    0
573    0
574    1
575    0
576    1
577    0
578    0
579    0
580    0
581    0
582    1
583    0
584    0
585    1
586    0
587    1
588    0
589    0
590    0
591    0
592    0
593    0
594    0
595    0
596    1
597    0
598    0
599    0
600    1
601    0
602    0
603    1
604    0
605    0
606    1
607    0
608    0
609    0
610    0
611    1
612    0
613    0
614    0
615    0
616    0
617    0
618    0
619    0
620    0
621    0
622    1
623    0
624    0
625    0
626    0
627    0
628    0
629    0
630    1
631    0
632    0
633    0
634    1
635    1
636    0
637    1
638    0
639    0
640    0
641    0
642    0
643    0
644    0
645    0
646    0
647    0
648    1
649    0
650    0
651    1
652    0
653    0
654    1
655    1
656    0
657    0
658    1
659    0
660    1
661    0
662    0
663    0
664    1
665    0
666    0
667    0
668    0
669    0
670    0
671    0
672    1
673    0
674    0
675    0
676    0
677    1
678    0
679    1
680    0
681    1
682    0
683    0
684    0
685    0
686    1
687    0
688    0
689    0
690    0
691    0
692    1
693    1
694    0
695    1
696    1
697    1
698    0
699    0
dtype: uint8

## Concatination

In [ ]:
df = pd.concat([df, reason_type1, reason_type2, reason_type3, reason_type4], axis=1)
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

In [ ]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

## Reorder columns

In [ ]:
column_names =['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

df.columns = column_names

In [ ]:
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason_1,Reason_2,Reason_3,Reason_4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

In [ ]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1',
       'Reason_2', 'Reason_3', 'Reason_4'], dtype=object)

In [ ]:
reordered_column = ['Reason_1',
       'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours'
       ]

In [ ]:
df = df[reordered_column]

In [ ]:
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

## Create checkpoint

In [ ]:
df_reason_mod = df.copy()

In [ ]:
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

## Date

In [ ]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format='%d/%m/%Y')

In [ ]:
df_reason_mod['Date'].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

## Month

In [ ]:
month_list = []
month_list

[]

In [ ]:
for i in range(len(df_reason_mod)):
  month_list.append(df_reason_mod['Date'][i].month)

In [ ]:
month_list

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5]

In [ ]:
df_reason_mod['Month Value'] = month_list

In [ ]:
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Value
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7

## Extract the weekday

In [ ]:
def date_to_weekday(date):
  return date.weekday()

In [ ]:
df_reason_mod['Day of the week'] = df_reason_mod['Date'].apply(date_to_weekday)

In [ ]:
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Value,Day of the week
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

In [ ]:
df_reason_mod = df_reason_mod.drop(['Date'], axis=1)

In [ ]:
df_reason_mod.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of the week'], dtype=object)

In [ ]:
new_columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month Value', 'Day of the week','Transportation Expense', 
       'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

df_reason_mod = df_reason_mod[new_columns]

In [ ]:
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,1,2,1,2

### Create Checkpoint

In [ ]:
df_reason_date_mod = df_reason_mod.copy()

## 'Children', 'Education' and 'Pets'

In [ ]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4])

In [ ]:
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [ ]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [ ]:
df_reason_date_mod['Education'].unique()

array([0, 1])

## Final Checkpoint

In [ ]:
df_preprocessed = df_reason_date_mod.copy()

In [ ]:
df_preprocessed.to_csv('Absenteeism_preprocessed.csv', index=False)

In [ ]:

df_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2